#!/usr/bin/env python3
"""Verify that the distributable GoDo core package works without optional integrations."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
FRAMEWORK_SOURCE = REPOSITORY_ROOT / "addons" / "godo_framework"
PROJECT_NAME = "GoDoCorePackageVerification"
OPTIONAL_DIRECTORIES = (
    "addons/guideCS",
    "addons/phantom_camera",
    "addons/godo_framework/Integrations/GuideInput",
    "addons/godo_framework/Integrations/PhantomCamera",
)

PROJECT_CONFIG = """; Engine configuration file.
; Generated by verify_core_package.py.
config_version=5

[application]

config/name="GoDo Core Package Verification"
run/main_scene="res://CoreSmoke.tscn"
config/features=PackedStringArray("4.7", "C#")

[autoload]

GoDoRuntime="*res://addons/godo_framework/Core/GoDoRuntime.tscn"

[dotnet]

project/assembly_name="GoDoCorePackageVerification"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
"""

PROJECT_FILE = """<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
</Project>
"""

SMOKE_SCENE = """[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://CoreSmoke.cs" id="1_runner"]

[node name="CoreSmoke" type="Node"]
script = ExtResource("1_runner")
"""

SMOKE_SCRIPT = """using System;
using Godot;
using GoDo;

#nullable enable

public sealed partial class CoreSmoke : Node
{
    public override void _Ready() => CallDeferred(MethodName.VerifyRuntime);

    private void VerifyRuntime()
    {
        try
        {
            _ = Services.Get<ISceneService>();
            _ = Services.Get<ICameraService>();
            _ = Services.Get<IInputService>();
            _ = Services.Get<IAudioService>();
            _ = Services.Get<ILocalizationService>();
            _ = Services.Get<IUiService>();
            _ = Services.Get<ISaveService>();
            _ = Services.Get<ISettingsService>();
            _ = Services.Get<IProcedureService>();

            GD.Print("[CorePackage] PASS (9/9 services)");
            GetTree().Quit(0);
        }
        catch (Exception exception)
        {
            GD.PushError($"[CorePackage] FAIL: {exception}");
            GetTree().Quit(1);
        }
    }
}
"""


def configure_console_encoding() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="在临时干净 Godot C# 项目中验证 GoDo 核心包。"
    )
    parser.add_argument(
        "--godot",
        type=Path,
        help="Godot 4.7.1 Mono Console 可执行文件；也可设置 GODOT_PATH。",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=60,
        help="Headless 运行超时秒数，默认 60。",
    )
    parser.add_argument(
        "--keep",
        action="store_true",
        help="失败排查时保留临时项目，并输出其路径。",
    )
    return parser.parse_args()


def resolve_godot_path(argument: Path | None) -> Path:
    candidates: list[str | Path | None] = [
        argument,
        os.environ.get("GODOT_PATH"),
        shutil.which("godot"),
        shutil.which("godot4"),
            shutil.which("Godot_v4.7.1-stable_mono_win64_console.exe"),
    ]
    for candidate in candidates:
        if candidate is None:
            continue
        path = Path(candidate).expanduser().resolve()
        if path.is_file():
            return path

    raise RuntimeError(
        "未找到 Godot 4.7.1 Mono Console；请使用 --godot <exe路径> 或设置 GODOT_PATH。"
    )


def run(command: list[str], cwd: Path, timeout: int | None = None) -> str:
    try:
        result = subprocess.run(
            command,
            cwd=cwd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as exception:
        output = (exception.stdout or "") + (exception.stderr or "")
        raise RuntimeError(f"命令超时：{' '.join(command)}\n{output}") from exception

    output = result.stdout + result.stderr
    if result.returncode == 0:
        return output

    raise RuntimeError(
        f"命令失败（exit={result.returncode}）：{' '.join(command)}\n"
        f"{output}"
    )


def create_project(project_root: Path) -> None:
    if not FRAMEWORK_SOURCE.is_dir():
        raise RuntimeError(f"未找到核心包目录：{FRAMEWORK_SOURCE}")

    shutil.copytree(
        FRAMEWORK_SOURCE,
        project_root / "addons" / "godo_framework",
        ignore=shutil.ignore_patterns("Integrations"),
    )
    (project_root / "project.godot").write_text(PROJECT_CONFIG, encoding="utf-8")
    (project_root / f"{PROJECT_NAME}.csproj").write_text(PROJECT_FILE, encoding="utf-8")
    (project_root / "CoreSmoke.tscn").write_text(SMOKE_SCENE, encoding="utf-8")
    (project_root / "CoreSmoke.cs").write_text(SMOKE_SCRIPT, encoding="utf-8")

    for relative_path in OPTIONAL_DIRECTORIES:
        if (project_root / relative_path).exists():
            raise RuntimeError(f"核心包验证项目包含了可选目录：{relative_path}")


def verify(project_root: Path, godot_path: Path, timeout: int) -> None:
    print(f"[BUILD] {PROJECT_NAME}.csproj")
    run(["dotnet", "build", f"{PROJECT_NAME}.csproj", "--nologo"], project_root)

    print("[RUN] CoreSmoke.tscn")
    output = run(
        [str(godot_path), "--headless", "--path", str(project_root), "res://CoreSmoke.tscn"],
        project_root,
        timeout,
    )
    if "[CorePackage] PASS (9/9 services)" not in output:
        raise RuntimeError(f"CoreSmoke 未输出成功标记。\n{output}")
    print("[PASS] 核心包可在无可选依赖的干净项目中编译并运行")


def main() -> int:
    configure_console_encoding()
    arguments = parse_arguments()
    if arguments.timeout <= 0:
        raise RuntimeError("--timeout 必须大于 0。")

    godot_path = resolve_godot_path(arguments.godot)
    if arguments.keep:
        project_root = Path(tempfile.mkdtemp(prefix="godo-core-package-"))
        try:
            create_project(project_root)
            verify(project_root, godot_path, arguments.timeout)
        except Exception:
            print(f"[KEEP] 临时项目保留在：{project_root}", file=sys.stderr)
            raise
        shutil.rmtree(project_root)
        return 0

    with tempfile.TemporaryDirectory(prefix="godo-core-package-") as temporary_directory:
        project_root = Path(temporary_directory)
        create_project(project_root)
        verify(project_root, godot_path, arguments.timeout)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError) as error:
        print(f"核心包验证失败：{error}", file=sys.stderr)
        raise SystemExit(1)
